name: CI

on:
  push:
    branches: ['main']

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, bcmath, intl, dom, fileinfo
          coverage: none

      - name: Instala dependências do PHP
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copia .env de teste
        run: cp .env.example .env

      - name: Gera chave de aplicação
        run: php artisan key:generate

      - name: Executa migrations
        run: php artisan migrate --force

      - name: Roda testes (PEST)
        run: ./vendor/bin/pest --verbose

      - name: Build frontend (React)
        run: |
          npm ci
          npm run build
